apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-pagamentos
  template:
    metadata:
      labels:
        app: flash-pagamentos
    spec:
      containers:
      - name: pagamentos
        image: eduratoo/flash-pagamentos
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
spec:
  selector:
    app: flash-pagamentos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP